name: flutter_mongo_realm_web
description: The web implementation of flutter_mongo_realm plugin
version: 0.1.0
homepage: https://github.com/tapLab/flutter_mongo_stitch_web
publish_to: none

environment:
    sdk: ">=2.7.0 <3.0.0"
    flutter: "2.10.5"

dependencies:
    flutter:
        sdk: flutter
    flutter_web_plugins:
        sdk: flutter

    # For supporting web sdk and js-dart inter-op
    js: ^0.6.3

    flutter_mongo_realm_platform_interface:
        git: https://github.com/tapLab/flutter_mongo_realm_platform_interface.git

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    assets:
        - assets/js/realmUtils.js
    plugin:
        platforms:
            web:
                pluginClass: FlutterMongoRealmPlugin
                fileName: flutter_mongo_realm_web.dart
