name: flutter_mongo_stitch_web
description: The web implementation of flutter_mongo_stitch plugin
version: 0.3.2
homepage: https://github.com/kfiross/flutter_mongo_stitch_platform_interface

environment:
    sdk: ">=2.7.0 <3.0.0"
    flutter: ">=1.10.0 <2.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_web_plugins:
        sdk: flutter

    # For supporting web sdk and js-dart inter-op
    js: ^0.6.2

    flutter_mongo_stitch_platform_interface: ^1.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    assets:
        - assets/js/test.txt
        - assets/js/stitchUtils.js
    plugin:
        platforms:
            web:
                pluginClass: FlutterMongoStitchPlugin
                fileName: flutter_mongo_stitch_web.dart
